### ISSUE TITLE
Enable $search filter in query

### ISSUE THREAD

**Issue by Brian-McBride** [Brian-McBride/feathers-arangodb#1]
### Feathers $search

Enabling the $search query/hook for feathers. https://docs.feathersjs.com/api/databases/querying.html#search

#### Overview
The $search filter could be a nice way to pass in a aql query object. This would override the mongo to aql conversion to reduce complexity.

#### Optional
Possibly adding in a $aql key/value pair detection in the params. If detected, the custom aql is run instead.

###### Security Concerns
The aql queries pose a significant security risk if allowed to be passed in through a REST or Socket transport.

**Comment by aguilera51284** [comment]
its alive this proyect???

**Comment by Brian-McBride** [comment]
I haven't been using Feathers, but I have been using ArangoDb for my graph DB uses. I don't think FeathersJS has changed their adapter structure, so this should still work. If you want to do a $search query, you'll probably just need to get a reference to the arangoDb and do whatever special sauce. Basic CRUD should be good. 

Looking at the repo, I see that there is a package vulnerability I'll make some time to update the package.json file. But if you want to do that and submit a PR, I'll happily merge in it.

**Comment by mindaugasnakrosis** [comment]
@Brian-McBride is possible atm to use aql with this adapter?

**Comment by Brian-McBride** [comment]
As I mentioned in this issue, I didn't add in a search method. Although, that's not super hard, I should.

In the meantime, you can access either the database or collection reference in the constructor.

```
yourServiceRef. _db            // Database
yourServiceRef. _colName // Collections
```

However, I remember feathers having a $search feature that would connect to this service. That would call an open query here. Next week, I can look into adding that.

**Comment by aguilera51284** [comment]
in my services ... _db is undefined :( 
```
// Initializes the `users` service on path `/users`
const createService = require('feathers-arangodb');
const hooks = require('./users.hooks');

module.exports = function (app) {

  const paginate = app.get('paginate');
  const arangoClient = app.get('arangoClient');

  const options = {
    paginate
  };

  // Initialize our service with any options it requires
  app.use('/users', createService(options));

  // Get our initialized service so that we can register hooks
  const service = app.service('users');

  arangoClient.then(db => {
    service.init(db, 'Users');
  });

  service.hooks(hooks);
};
```

**Comment by Brian-McBride** [comment]
@aguilera51284 and @Elminday
I went ahead and updated the libs. 
`"@feathersjs/commons": "^1.4.4",` is still hanging at 1.4.4 instead of 3.x.x. matching the feathers-mongo repo (which this is templated off of)

Further, I added in an additional method to the server called `query` and that maps directly to the database query. I threw up an example on how to use it in the docs. Anywhere you have access to the Feathers' context object that your ArangoDB service is attached to, you should be good to go. 

Keep in mind, I am also returning the cursor object. So you'll need to handle that async call in some way. But this should get solid AQL query results.

Feel free to add pull requests and expand the functionality.
