### ISSUE TITLE
Where can I set the host for the database?

### ISSUE THREAD

**Issue by smyth64** [Brian-McBride/feathers-arangodb#11]
Couldn't find anything. So where can I change the host of my arangodb?

**Comment by Brian-McBride** [comment]
It's part of the dbConfig
Check the readme and you'll see a list of key/values you can pass into the service. 

The dbConfig is a standard ArangoDB configuration object. The link to the ArangoDB docs is there as well for reference.

**Comment by Brian-McBride** [comment]
Quick (partial) code example:
```javascript
const todoDatabase = {  
  collection: 'TODOS',  
  database: 'YOUR_DATABASE_NAME',  
  authType: AUTH_TYPES.BASIC_AUTH,  
  username: 'root',  
  password: 'root',
  dbConfig: {
    url: 'http://localhost:8529',
    agentOptions: {maxSockets: 3, keepAlive: true, keepAliveMsecs: 1000},
    maxRetries: 5
  }
};  

app.use('todos', ArangoDbService(todoDatabase));
```

Hopefully you are set and going!

**Comment by smyth64** [comment]
@Brian-McBride Thanks for your fast reaction.

Unfortunately it doesn't work. It works when I add this ({url: 'http://my-domain.com:8529'}) to the connect () function

```
    async connect() {
        const { authType, username, password, token, graph } = this.options;
        /* istanbul ignore next */
        if (this._database === undefined) {
            this._database = new auto_database_1.AutoDatabse({url: 'http://my-domain.com:8529'});
            // instead of
            this._database = new auto_database_1.AutoDatabse({url: 'http://my-domain.com:8529'});
```

**Comment by Brian-McBride** [comment]
Thanks for finding this. The dbOptions where not being passed into the new database creation in the automatic path. 

I just pushed up a new version to npm and added a unit test for custom URLs.

**Comment by smyth64** [comment]
@Brian-McBride Awesome, thank you :)
